### ISSUE TITLE
Install server crashes app - memory issue

### ISSUE THREAD

**Issue by laser-brain** [vhqtvn/VHEditor-Android#121]
The latest version 1.7.1 crashes when trying to install the server. Adb logcat output shows a java.lang.OutOfMemoryException.
Any way to optimize here for less memory usage?

```
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at vn.vhn.vhscode.CodeServerService$Companion.getZip(Native method)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at vn.vhn.vhscode.CodeServerService$Companion.c(SourceFile:22)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at vn.vhn.vhscode.MainActivity$b$b.b(SourceFile:5)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at f.j.j.a.a.d(SourceFile:2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.h0.a(SourceFile:18)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.b.a(SourceFile:34)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.b.k(SourceFile:2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.b.h(SourceFile:3)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.i.q(SourceFile:5)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at b.a.r1.b$a.run(SourceFile:1)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at android.os.Handler.handleCallback(Handler.java:938)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at android.os.Handler.dispatchMessage(Handler.java:99)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at android.os.Looper.loop(Looper.java:223)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at android.app.ActivityThread.main(ActivityThread.java:7791)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at java.lang.reflect.Method.invoke(Native method)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655] Pending exception java.lang.OutOfMemoryError: Failed to allocate a 180148616 byte allocation with 3282159 free bytes and 124MB until OOM, target footprint 6564319, growth limit 134217728
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at byte[] vn.vhn.vhscode.CodeServerService$Companion.getZip() (SourceFile:-2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at java.lang.Object vn.vhn.vhscode.CodeServerService$Companion.c(android.content.Context, b.a.s1.f, f.j.d) (SourceFile:22)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at java.lang.Object vn.vhn.vhscode.MainActivity$b$b.b(java.lang.Object) (SourceFile:5)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void f.j.j.a.a.d(java.lang.Object) (SourceFile:2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void b.a.h0.a(b.a.i0, f.j.d, int) (SourceFile:18)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void b.a.b.a(b.a.i1, java.lang.Object, int) (SourceFile:34)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at boolean b.a.b.k(b.a.i1, java.lang.Object, int) (SourceFile:2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void b.a.b.h(java.lang.Object, int) (SourceFile:3)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void b.a.i.q(b.a.v, java.lang.Object) (SourceFile:5)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void b.a.r1.b$a.run() (SourceFile:1)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:938)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:99)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void android.os.Looper.loop() (Looper.java:223)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:7791)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:592)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655]   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:952)
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:655] 
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: java_array == null
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:663]     in call to SetPrimitiveArrayRegion
03-29 23:20:15.496 26601 26601 F vn.vhn.vsc: runtime.cc:663]     from byte[] vn.vhn.vhscode.CodeServerService$Companion.getZip()
03-29 23:20:15.496 26601 26601 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 26601 (vn.vhn.vsc), pid 26601 (vn.vhn.vsc)

```

**Comment by laser-brain** [comment]
Might be related to #55 
As far as I understand the code, the issue is rooted in the C module loading the zip file
