### ISSUE TITLE
can't run on Android

### ISSUE THREAD

**Issue by Sifatplayz** [vhqtvn/VHEditor-Android#161]
When i try to run after installing server 
it crush's i cant open the editor.
When i reopen the app it completely goes black & exit out the app.
Before some version i could use it.But in the last 3/4 i could not use vheditor.

**Comment by vhqtvn** [comment]
I'm using android 11 too not having any problem on both of my devices.

Please install 2.6.0 it should display a crash message and copy details here.

**Comment by Sifatplayz** [comment]
g3.a
g3.a

g3.a: /data/data/vn.vhn.vsc/files/usr/lib/libc++_shared.so: The source file doesn't exist.
	at g3.d.T(SourceFile:18)
	at a1.a.B(SourceFile:42)
	at l4.k.run(SourceFile:2)
	at com.termux.app.TermuxInstaller.c(SourceFile:7)
	at vn.vhn.vhscode.root.NewSessionActivity.onStartCode(SourceFile:3)
	at vn.vhn.vhscode.root.NewSessionActivity.x(SourceFile:10)
	at l4.q.e(SourceFile:4)
	at c3.a.n(SourceFile:4)
	at r3.c0.run(SourceFile:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:255)
	at android.app.ActivityThread.main(ActivityThread.java:8224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)


Android Version: 30
Device Manufacturer: realme
Device Model: RMX2189

**Comment by Sifatplayz** [comment]
Here is the errors

**Comment by vhqtvn** [comment]
Try resetting rootfs.

**Comment by Sifatplayz** [comment]
When the server is installed it swipes left & exit
i tried resetting the rootfs

**Comment by vhqtvn** [comment]
Please start a termux session and check if `/data/data/vn.vhn.vsc/files/usr/lib/libc++_shared.so` exists.

**Comment by Sifatplayz** [comment]
> From the trace it suggested that the above shared library does not exists, try resetting root fs, force close the app and then start again to install server, or just delete the app and reinstall again (backup your home folder first).

doesn't work😐

**Comment by vhqtvn** [comment]
Please make a video after you deleted the app.

**Comment by Sifatplayz** [comment]
> Please make a video after you deleted the app.
> 

how do i sent you the video?

**Comment by vhqtvn** [comment]
Just post it on this thread or mail me at ***@***.***

**Comment by Sifatplayz** [comment]
> Just post it on this thread or mail me at ***@***.***
> 
> > Message ID: ***@***.***>
> >
> 

its showing ***@***.***
"*" so try using a ! after each letter

**Comment by vhqtvn** [comment]
Hmm it's vscode [at] vhn.vn.

**Comment by Sifatplayz** [comment]
does new release solve the problem?

**Comment by Sifatplayz** [comment]
check your mail

**Comment by vhqtvn** [comment]
Hm I dont see any...

**Comment by vhqtvn** [comment]
Please try the latest version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.7.2

**Comment by Sifatplayz** [comment]
> Please try the latest version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.7.2

doesn't work :"(

**Comment by vhqtvn** [comment]
Yes but it should show the install log if there is install error?

**Comment by Sifatplayz** [comment]
> Yes but it should show the install log if there is install error?

i didn't saw any issues in installing
the issues is i cant open editor

if i tap on ***Start Editor*** it goes black & exit the app

**Comment by vhqtvn** [comment]
Yes above error reported that the server files is not installed after installed, strange, I'll update next resolution soon.

**Comment by ElvEvosoftOlav** [comment]
an example of a cellphone case that has the same problem is Vivo y15s late version

**Comment by Sifatplayz** [comment]
will the new version work?
is it fixed?

**Comment by Sifatplayz** [comment]
Still can't open but
in previous version when i tried to use start editor by default it just exit the app & if i re-enter the app it exits again
it is fixed a little bit but still not fixed

**Comment by vhqtvn** [comment]
Yes I still can not find a reason for this bug, the new versions are just ci testing.

**Comment by srmaaman** [comment]
I have Android 11. This is not reading my phone internal storage. It'll be wasted for me without this.

**Comment by vhqtvn** [comment]
I dont understand? Check if you already gave permissions to the app?

**Comment by Sifatplayz** [comment]
> I dont understand? Check if you already gave permissions to the app?

it has permission
also let me check the newest release

**Comment by vhqtvn** [comment]
Please try this version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.9.4-test.0

**Comment by Sifatplayz** [comment]
still not fixed 😞

**Comment by Sifatplayz** [comment]
When it will be fixed??

**Comment by ifedayoprince** [comment]
VhEditor version 2.10.0 is crashing on my device. 

My device is Infinix Smart 6, and it is running Android 11. Please fix, I have a serious project to work on.

**Comment by Sifatplayz** [comment]
@vhqtvn when it will be fixed?

**Comment by vhqtvn** [comment]
Still the same error right? 
Seems that your device somehow blocked/removed above libc from copying/loading.

Can you use the terminal part?

**Comment by ifedayoprince** [comment]
> Still the same error right? Seems that your device somehow blocked/removed above libc from copying/loading.
> 
> Can you use the terminal part?

Yes

**Comment by ifedayoprince** [comment]
I just updated to version 2.12.0 but it still crashes.

**Comment by ifedayoprince** [comment]
When I run the boot.sh from the terminal, I get something like a ".pid" does not exist. I'm still scanning everything though. Hope a fix comes out soon.

**Comment by vhqtvn** [comment]
That c++ shared should be copied to `files/`, node will use it there. When you start the server it will create a file named `run-vs-code.sh`:

https://github.com/vhqtvn/VHEditor-Android/blob/master/app/src/main/java/vn/vhn/vhscode/root/codeserver/CodeServerLocalService.kt#L147

You can try to run it from the commandline to check error ̣(run `$(echo -n "env "; cat run-vs-code.sh)`).

**Comment by Sifatplayz** [comment]
> Still the same error right? 
> Seems that your device somehow blocked/removed above libc from copying/loading.
> 
> Can you use the terminal part?

yes i can.

**Comment by Sifatplayz** [comment]
> That c++ shared should be copied to `files/`, node will use it there. When you start the server it will create a file named `run-vs-code.sh`:
> 
> https://github.com/vhqtvn/VHEditor-Android/blob/master/app/src/main/java/vn/vhn/vhscode/root/codeserver/CodeServerLocalService.kt#L147
> 
> You can try to run it from the commandline to check error ̣(run `$(echo -n "env "; cat run-vs-code.sh)`).

I tried this and this is what the terminal says
```
~ $ $(echo -n "env "; cat run-vs-code.sh)
cat: run-vs-code.sh: No such file or directory
SHELL=/data/data/vn.vhn.vsc/files/usr/bin/bash
HISTCONTROL=ignoreboth
PREFIX=/data/data/vn.vhn.vsc/files
NODE_OPTIONS="--require=/data/data/vn.vhn.vsc/files/globalinject.js"
TERMUX_PKG_NO_MIRROR_SELECT=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
PWD=/data/data/vn.vhn.vsc/files/home
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/vn.vhn.vsc/files/usr/lib/libtermux-exec.so
HOME=/data/data/vn.vhn.vsc/files/home
LANG=en_US.UTF-8
TMPDIR=/data/data/vn.vhn.vsc/files/tmp
ANDROID_DATA=/data
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/oplus-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/com.android.fmradio.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-ims-base.jar:/system/framework/mediatek-telecom-common.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar
LD_LIBRARY_PATH=/data/data/vn.vhn.vsc/files:/data/data/vn.vhn.vsc/files/usr/lib
ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
PATH=/data/data/vn.vhn.vsc/files/bin:/data/data/vn.vhn.vsc/files/usr/bin:/data/data/vn.vhn.vsc/files/usr/bin/applets
_=/data/data/vn.vhn.vsc/files/usr/bin/env
```

**Comment by vhqtvn** [comment]
you should run the editor once so the sh file created.

**Comment by Sifatplayz** [comment]
> you should run the editor once so the sh file created.

i just tap on the app then tap on install server the. start editor

then the screen goes black & exit the app

**Comment by Sifatplayz** [comment]
> you should run the editor once so the sh file created.

when i run
```
cat /data/data/vn.vhn.vsc/files/usr/lib/libc++_shared.so
```
this happens

![Screenshot_2022-11-21-11-09-01-90_9c1589490c906a9623165cad7a860a58.jpg](https://user-images.githubusercontent.com/90343181/202970356-5ef01165-ca2b-422c-8f4f-ee9dc7b8fd24.jpg)![Screenshot_2022-11-21-11-06-59-09_9c1589490c906a9623165cad7a860a58.jpg](https://user-images.githubusercontent.com/90343181/202970369-21226684-0c32-4024-9fa3-99f1c333a8fc.jpg)

**Comment by vhqtvn** [comment]
Yes run the last command now.

**Comment by Sifatplayz** [comment]
> Yes run the last command now.

last command?

you mean this?
```
cat /data/data/vn.vhn.vsc/files/usr/lib/libc++_shared.so
```

**Comment by vhqtvn** [comment]
`$(echo -n "env "; cat run-vs-code.sh)`

**Comment by Sifatplayz** [comment]
> `$(echo -n "env "; cat run-vs-code.sh)`

here is the log
```
~ $ $(echo -n "env "; cat run-vs-code.sh)
cat: run-vs-code.sh: No such file or directory
SHELL=/data/data/vn.vhn.vsc/files/usr/bin/bash
HISTCONTROL=ignoreboth
PREFIX=/data/data/vn.vhn.vsc/files
NODE_OPTIONS="--require=/data/data/vn.vhn.vsc/files/globalinject.js"
TERMUX_PKG_NO_MIRROR_SELECT=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
PWD=/data/data/vn.vhn.vsc/files/home
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/vn.vhn.vsc/files/usr/lib/libtermux-exec.so
HOME=/data/data/vn.vhn.vsc/files/home
LANG=en_US.UTF-8
TMPDIR=/data/data/vn.vhn.vsc/files/tmp
ANDROID_DATA=/data
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/oplus-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/com.android.fmradio.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-ims-base.jar:/system/framework/mediatek-telecom-common.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar
LD_LIBRARY_PATH=/data/data/vn.vhn.vsc/files:/data/data/vn.vhn.vsc/files/usr/lib
ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
PATH=/data/data/vn.vhn.vsc/files/bin:/data/data/vn.vhn.vsc/files/usr/bin:/data/data/vn.vhn.vsc/files/usr/bin/applets
_=/data/data/vn.vhn.vsc/files/usr/bin/env
```

**Comment by Sifatplayz** [comment]
> `$(echo -n "env "; cat run-vs-code.sh)`

here is the log
```
~ $ $(echo -n "env "; cat run-vs-code.sh)
cat: run-vs-code.sh: No such file or directory
SHELL=/data/data/vn.vhn.vsc/files/usr/bin/bash
HISTCONTROL=ignoreboth
PREFIX=/data/data/vn.vhn.vsc/files
NODE_OPTIONS="--require=/data/data/vn.vhn.vsc/files/globalinject.js"
TERMUX_PKG_NO_MIRROR_SELECT=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
PWD=/data/data/vn.vhn.vsc/files/home
EXTERNAL_STORAGE=/sdcard
LD_PRELOAD=/data/data/vn.vhn.vsc/files/usr/lib/libtermux-exec.so
HOME=/data/data/vn.vhn.vsc/files/home
LANG=en_US.UTF-8
TMPDIR=/data/data/vn.vhn.vsc/files/tmp
ANDROID_DATA=/data
TERM=xterm-256color
SHLVL=1
ANDROID_ROOT=/system
BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/oplus-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/com.android.fmradio.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-ims-base.jar:/system/framework/mediatek-telecom-common.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar
LD_LIBRARY_PATH=/data/data/vn.vhn.vsc/files:/data/data/vn.vhn.vsc/files/usr/lib
ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
PATH=/data/data/vn.vhn.vsc/files/bin:/data/data/vn.vhn.vsc/files/usr/bin:/data/data/vn.vhn.vsc/files/usr/bin/applets
_=/data/data/vn.vhn.vsc/files/usr/bin/env
```

**Comment by Sifatplayz** [comment]
> > `$(echo -n "env "; cat run-vs-code.sh)`
> 
> here is the log.
> 
> see the second line
> `cat: run-vs-code.sh: No such file or directory`
> ```
> ~ $ $(echo -n "env "; cat run-vs-code.sh)
> cat: run-vs-code.sh: No such file or directory
> SHELL=/data/data/vn.vhn.vsc/files/usr/bin/bash
> HISTCONTROL=ignoreboth
> PREFIX=/data/data/vn.vhn.vsc/files
> NODE_OPTIONS="--require=/data/data/vn.vhn.vsc/files/globalinject.js"
> TERMUX_PKG_NO_MIRROR_SELECT=1
> TERMUX_MAIN_PACKAGE_FORMAT=debian
> PWD=/data/data/vn.vhn.vsc/files/home
> EXTERNAL_STORAGE=/sdcard
> LD_PRELOAD=/data/data/vn.vhn.vsc/files/usr/lib/libtermux-exec.so
> HOME=/data/data/vn.vhn.vsc/files/home
> LANG=en_US.UTF-8
> TMPDIR=/data/data/vn.vhn.vsc/files/tmp
> ANDROID_DATA=/data
> TERM=xterm-256color
> SHLVL=1
> ANDROID_ROOT=/system
> BOOTCLASSPATH=/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/oplus-framework.jar:/system/framework/coloros-support-wrapper.jar:/system/framework/ifaamanager.jar:/system/framework/com.android.fmradio.jar:/system/framework/mediatek-telephony-base.jar:/system/framework/mediatek-telephony-common.jar:/system/framework/mediatek-common.jar:/system/framework/mediatek-framework.jar:/system/framework/mediatek-ims-common.jar:/system/framework/mediatek-ims-base.jar:/system/framework/mediatek-telecom-common.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar
> LD_LIBRARY_PATH=/data/data/vn.vhn.vsc/files:/data/data/vn.vhn.vsc/files/usr/lib
> ANDROID_TZDATA_ROOT=/apex/com.android.tzdata
> PATH=/data/data/vn.vhn.vsc/files/bin:/data/data/vn.vhn.vsc/files/usr/bin:/data/data/vn.vhn.vsc/files/usr/bin/applets
> _=/data/data/vn.vhn.vsc/files/usr/bin/env
> ```

I also found that when i install the server
6850/6880 is installed.

**Comment by Sifatplayz** [comment]
arm64 is working but its very lagggggggy
