### ISSUE TITLE
just about to start editor it shows white screen and close/clashes (using 32bit Samsung android 11)

### ISSUE THREAD

**Issue by Williammmmmmmmmmm** [vhqtvn/VHEditor-Android#178]
This is a great project, only if these icompability issues would be solved with others devices. Please help and give some feedback when these will be worked at in which version, looking forward in using it on my same device

**Comment by vhqtvn** [comment]
Please take screenshot of the log overlay (3 fingers up).

**Comment by Williammmmmmmmmmm** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.vhn.vsc/vn.vhn.vhscode.root.NewSessionActivity}: android.system.ErrnoException: symlink failed: EEXIST (File exists)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3835)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4011)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2325)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.system.ErrnoException: symlink failed: EEXIST (File exists)
	at libcore.io.Linux.symlink(Native Method)
	at libcore.io.ForwardingOs.symlink(ForwardingOs.java:227)
	at libcore.io.BlockGuardOs.symlink(BlockGuardOs.java:406)
	at libcore.io.ForwardingOs.symlink(ForwardingOs.java:227)
	at android.system.Os.symlink(Os.java:677)
	at vn.vhn.vhscode.service_features.SetupCodeServerKt.initialSetupIfNeededSync(setupCodeServer.kt:15)
	at vn.vhn.vhscode.root.NewSessionActivity.onCreate(NewSessionActivity.kt:7)
	at android.app.Activity.performCreate(Activity.java:8207)
	at android.app.Activity.performCreate(Activity.java:8191)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3808)
	... 11 more
