### ISSUE TITLE
Crash on Android 11; OPPO F15

### ISSUE THREAD

**Issue by Itz-coded-by-me** [vhqtvn/VHEditor-Android#216]
android.view.InflateException
android.view.InflateException

android.view.InflateException: Binary XML file line #21 in vn.vhn.vsc:layout/fragment_v_s_code: Binary XML file line #21 in vn.vhn.vsc:layout/fragment_v_s_code: Error inflating class vn.vhn.vhscode.chromebrowser.VSCodeBrowser
Caused by: android.view.InflateException: Binary XML file line #21 in vn.vhn.vsc:layout/fragment_v_s_code: Error inflating class vn.vhn.vhscode.chromebrowser.VSCodeBrowser
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1008)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1141)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1099)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at vn.vhn.vhscode.databinding.FragmentVSCodeBinding.inflate(FragmentVSCodeBinding.java:2)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.onCreateView(VSCodeFragment.kt:7)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:20)
	at androidx.fragment.app.l.createView(FragmentStateManager.java:177)
	at androidx.fragment.app.l.moveToExpectedState(FragmentStateManager.java:113)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:278)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:85)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:32)
	at androidx.fragment.app.a.commitNow(BackStackRecord.java:7)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:126)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:2)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView$e.addView(RecyclerView.java:8)
	at androidx.recyclerview.widget.b.addView(ChildHelper.java:6)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:113)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:35)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:357)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:39)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:41)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:6)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:71)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:71)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:57)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:71)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:875)
	at android.view.View.layout(View.java:23304)
	at android.view.ViewGroup.layout(ViewGroup.java:6539)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3988)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3389)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2354)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9089)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1452)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1250)
	at android.view.Choreographer.doFrame(Choreographer.java:926)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1437)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:8312)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:271)
	at android.webkit.WebView.getFactory(WebView.java:2585)
	at android.webkit.WebView.ensureProviderCreated(WebView.java:2579)
	at android.webkit.WebView.setOverScrollMode(WebView.java:2663)
	at android.view.View.<init>(View.java:5391)
	at android.view.View.<init>(View.java:5548)
	at android.view.ViewGroup.<init>(ViewGroup.java:700)
	at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
	at android.webkit.WebView.<init>(WebView.java:422)
	at android.webkit.WebView.<init>(WebView.java:364)
	at android.webkit.WebView.<init>(WebView.java:346)
	at android.webkit.WebView.<init>(WebView.java:333)
	at vn.vhn.vhscode.chromebrowser.VSCodeBrowser.<init>(VSCodeBrowser.kt:6)
	... 78 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:266)
	... 90 more
Caused by: Ib0: errorCode=2
	at org.chromium.base.library_loader.b.g(chromium-SystemWebViewGoogle.aab-stable-535906100:128)
	at org.chromium.base.library_loader.b.i(chromium-SystemWebViewGoogle.aab-stable-535906100:25)
	at org.chromium.android_webview.AwBrowserProcess.j(chromium-SystemWebViewGoogle.aab-stable-535906100:32)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(chromium-SystemWebViewGoogle.aab-stable-535906100:457)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForR.<init>(chromium-SystemWebViewGoogle.aab-stable-535906100:1)
	at com.android.webview.chromium.WebViewChromiumFactoryProviderForR.create(chromium-SystemWebViewGoogle.aab-stable-535906100:3)
	... 92 more
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~wJ48O8n4Dhy0WwoeS4suJg==/com.google.android.webview-A6AOI5Do-QMvpxkNWGzJuw==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
	at java.lang.System.loadLibrary(System.java:1664)
	at org.chromium.base.library_loader.b.g(chromium-SystemWebViewGoogle.aab-stable-535906100:45)
	... 97 more

Android Version: 30
Device Manufacturer: OPPO
Device Model: CPH2001

**Comment by vhqtvn** [comment]
Please recheck with latest version.
