### ISSUE TITLE
Bug issue 

### ISSUE THREAD

**Issue by Mozzaru** [vhqtvn/VHEditor-Android#227]
com.facebook.react.common.JavascriptException: SyntaxError: /data/data/vn.vhn.vsc/files/home/vhe-modules/new-session.js: Missing semicolon. (1:2)

> 1 | MB ya ya bc export {main} from "./new-session-default"
    |   ^
  2 |

This error is located at:
    in Unknown
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in b, stack:
N@720:1863
value@720:68099
value@720:74483
value@720:291730
value@720:143834
value@720:292596
value@720:292432
value@720:279143
value@720:278753
value@720:164030
value@720:316147
<unknown>@720:316831
<unknown>@896:498
generatorResume@-1
<unknown>@905:465
generatorResume@-1
b@767:2335
transform@571:1712
compile@387:1551
load@387:1911
load_sync@387:2559
<unknown>@387:3073
<unknown>@1064:15142
<unknown>@387:2975
<unknown>@6:173
jr@31:43618
Na@31:95239
Ri@31:86336
_i@31:86264
Ei@31:86029
yi@31:82985
yi@-1
xt@31:27509
ci@31:79668
Zi@31:94613
<unknown>@31:100839
<unknown>@345:685
run@336:803
runApplication@336:1844
value@61:3821
<unknown>@61:759
value@61:2583
value@61:731
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:76)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:149)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:140)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
	at android.os.Looper.loop(Looper.java:263)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:38)
	at java.lang.Thread.run(Thread.java:923)

**Comment by vhqtvn** [comment]
You modified `/data/data/vn.vhn.vsc/files/home/vhe-modules/new-session.js` with invalid data, delete it to have it reset to default content or fix the file yourself.
