### ISSUE TITLE
[Crashed] java.lang.RuntimeException

### ISSUE THREAD

**Issue by AWATV** [vhqtvn/VHEditor-Android#241]
### Info

OS: Android 10
Model: Lenovo TB-X306X

### Logs
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{vn.vhn.vsc/vn.vhn.vhscode.root.NewSessionActivity}: android.system.ErrnoException: symlink failed: ENOENT (No such file or directory)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.system.ErrnoException: symlink failed: ENOENT (No such file or directory)
	at libcore.io.Linux.symlink(Native Method)
	at libcore.io.ForwardingOs.symlink(ForwardingOs.java:228)
	at libcore.io.BlockGuardOs.symlink(BlockGuardOs.java:404)
	at libcore.io.ForwardingOs.symlink(ForwardingOs.java:228)
	at android.system.Os.symlink(Os.java:675)
	at vn.vhn.vhscode.service_features.SetupCodeServerKt.initialSetupIfNeededSync(setupCodeServer.kt:150)
	at vn.vhn.vhscode.root.NewSessionActivity.onCreate(NewSessionActivity.kt:53)
	at android.app.Activity.performCreate(Activity.java:7862)
	at android.app.Activity.performCreate(Activity.java:7851)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
	... 11 more
```

**Comment by AWATV** [comment]
This error message indicates that a failure occurred while attempting to create a symbolic link in the `NewSessionActivity` of the `vn.vhn.vsc` Android application. The error is specifically caused by an `ENOENT` error, which typically indicates that the file or directory being referenced does not exist.

The error is occurring in the `initialSetupIfNeededSync` function of the `setupCodeServer.kt` file, which is called during the onCreate method of the `NewSessionActivity`.

To resolve this issue, it is recommended to verify that the files and directories being referenced in the `symlink` call exist. Additionally, it may be necessary to ensure that the application has the necessary file permissions or to run the application with elevated privileges. It may also be helpful to review any additional error messages or stack traces that provide more context for the issue.
