### ISSUE TITLE
Cant start editor

### ISSUE THREAD

**Issue by Zeuroux** [vhqtvn/VHEditor-Android#300]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	... 1 more
Caused by: java.lang.NoSuchMethodException: android.view.PointerIcon.load [class android.content.Context]
	at java.lang.Class.getMethod(Class.java:2950)
	at java.lang.Class.getDeclaredMethod(Class.java:2929)
	at vn.vhn.virtualmouse.MouseView$Companion.initPointerHack(MouseView.kt:585)
	at vn.vhn.virtualmouse.MouseView$Companion.access$initPointerHack(MouseView.kt:1)
	at vn.vhn.virtualmouse.MouseView.initialize(MouseView.kt:111)
	at vn.vhn.virtualmouse.VirtualMouse.enable(VirtualMouse.kt:115)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.configureVirtualMouseMode(VSCodeFragment.kt:48)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.onResume(VSCodeFragment.kt:29)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:18)
	at androidx.fragment.app.l.resume(FragmentStateManager.java:122)
	at androidx.fragment.app.l.moveToExpectedState(FragmentStateManager.java:57)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:278)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:85)
	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:32)
	at androidx.fragment.app.a.commitNow(BackStackRecord.java:7)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(FragmentStateAdapter.java:177)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(FragmentStateAdapter.java:132)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:2)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(FragmentStateAdapter.java:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(RecyclerView.java:14)
	at androidx.recyclerview.widget.RecyclerView$e.addView(RecyclerView.java:8)
	at androidx.recyclerview.widget.b.addView(ChildHelper.java:6)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(RecyclerView.java:113)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:2)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(RecyclerView.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:35)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:357)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:39)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:41)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:6)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at androidx.viewpager2.widget.ViewPager2.onLayout(ViewPager2.java:71)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:71)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:57)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:71)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6465)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4562)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9941)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8594)
	... 3 more

**Comment by Minigroom100** [comment]
How did you fix this error?

**Comment by vhqtvn** [comment]
The latest version should fix the problem.
