### ISSUE TITLE
Crashed again

### ISSUE THREAD

**Issue by Ahmadrezalbs** [vhqtvn/VHEditor-Android#302]
java.lang.NullPointerException: null receiver
	at java.lang.reflect.Method.invoke(Native Method)
	at vn.vhn.virtualmouse.MouseView.initialize(SourceFile:176)
	at vn.vhn.virtualmouse.VirtualMouse.enable(SourceFile:115)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.configureVirtualMouseMode(SourceFile:48)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.onResume(SourceFile:29)
	at androidx.fragment.app.Fragment.performResume(SourceFile:18)
	at androidx.fragment.app.y1.resume(SourceFile:120)
	at androidx.fragment.app.y1.moveToExpectedState(SourceFile:58)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:278)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:85)
	at androidx.fragment.app.FragmentManager.execSingleAction(SourceFile:32)
	at androidx.fragment.app.a.commitNow(SourceFile:7)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(SourceFile:177)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(SourceFile:133)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:2)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(SourceFile:14)
	at androidx.recyclerview.widget.o1.addView(SourceFile:8)
	at androidx.recyclerview.widget.l.addView(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(SourceFile:114)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:35)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:358)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:39)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:41)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:6)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at androidx.viewpager2.widget.ViewPager2.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(SourceFile:57)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1857)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1701)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1610)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:334)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1146)
	at android.view.View.layout(View.java:22496)
	at android.view.ViewGroup.layout(ViewGroup.java:6528)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3743)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3207)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by vhqtvn** [comment]
Please test this version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.18.1-0

**Comment by Ahmadrezalbs** [comment]
> Please test this version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.18.1-0

Problem fixed, thank you.
