### ISSUE TITLE
VH editor Crashed

### ISSUE THREAD

**Issue by AnkushYT248** [vhqtvn/VHEditor-Android#303]
Device: Infinix note 30 5G

### Bug
![Screenshot_20241009-142732](https://github.com/user-attachments/assets/e4048464-487b-4fea-808f-0e9eb2918667)

java.lang.NullPointerException: null receiver
	at java.lang.reflect.Method.invoke(Native Method)
	at vn.vhn.virtualmouse.MouseView.initialize(SourceFile:176)
	at vn.vhn.virtualmouse.VirtualMouse.enable(SourceFile:115)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.configureVirtualMouseMode(SourceFile:48)
	at vn.vhn.vhscode.root.fragments.VSCodeFragment.onResume(SourceFile:29)
	at androidx.fragment.app.Fragment.performResume(SourceFile:18)
	at androidx.fragment.app.y1.resume(SourceFile:120)
	at androidx.fragment.app.y1.moveToExpectedState(SourceFile:58)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:278)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:85)
	at androidx.fragment.app.FragmentManager.execSingleAction(SourceFile:32)
	at androidx.fragment.app.a.commitNow(SourceFile:7)
	at androidx.viewpager2.adapter.FragmentStateAdapter$FragmentMaxLifecycleEnforcer.updateFragmentMaxLifecycle(SourceFile:177)
	at androidx.viewpager2.adapter.FragmentStateAdapter.placeFragmentInViewHolder(SourceFile:133)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:2)
	at androidx.viewpager2.adapter.FragmentStateAdapter.onViewAttachedToWindow(SourceFile:1)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildAttached(SourceFile:14)
	at androidx.recyclerview.widget.o1.addView(SourceFile:8)
	at androidx.recyclerview.widget.l.addView(SourceFile:6)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addViewInt(SourceFile:114)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:2)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.addView(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(SourceFile:35)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(SourceFile:39)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(SourceFile:358)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(SourceFile:39)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(SourceFile:41)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:6)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at androidx.viewpager2.widget.ViewPager2.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(SourceFile:57)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:71)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:812)
	at android.view.View.layout(View.java:24610)
	at android.view.ViewGroup.layout(ViewGroup.java:6551)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4539)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3846)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2690)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9890)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1506)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1515)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1085)
	at android.view.Choreographer.doFrame(Choreographer.java:977)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1489)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:243)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:8446)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1064)
![Uploading Screenshot_20241009-142732.jpg…]()

**Comment by vhqtvn** [comment]
Please try this version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.18.1-0

**Comment by RIFAT567** [comment]
Same problem on the latest version but doesn't happen in v2.18.1-0. Any update coming with fix?

**Comment by vhqtvn** [comment]
Released new version.

**Comment by RIFAT567** [comment]
Thank you bro you're an og
