### ISSUE TITLE
Install server crash

### ISSUE THREAD

**Issue by frikinside** [vhqtvn/VHEditor-Android#55]
Hi!
I was trying to use this app on a low end tablet (if that's relevant) a Jusyea J5 with Android 10.
First I download the app from the Play Store and at launch tells me to download from github instead due to limitations of Play Store.
I uninstall the app and proceed to download and install the apk from github (arm version). It install fine, and at launch it promptme to install server, so I did, but the progressbar didn't move a bit (it stays at 0/0) and a few seconds later, the app crash.

I tried several times with the same result. Could you help me with this issue?

**Comment by vhqtvn** [comment]
Hm i dont install any crash analytic tools into the app so i cant check what's wrong now. That step is only extracting files so crashing there seems unlikely.
Anw your device seems to be 64 bit, please download aarch64 version and try again.

**Comment by frikinside** [comment]
I download the arm64 version and tried to install but it only shows "App not installed".
I try it several times (maybe the file was wrongly donwloaded or corrupted) with no success :(

Can I try anything else?

**Comment by vhqtvn** [comment]
Can you please download CPUZ and post sceenshot of the cpu section here?

**Comment by frikinside** [comment]
Sure thing! 
![Screenshot_20210618-173406](https://user-images.githubusercontent.com/13966372/122585763-228a7500-d05c-11eb-9888-8ac6f69c9373.png)

**Comment by vhqtvn** [comment]
Please check on system tab to see if it's 32 or 64 bit.
Googling the chip name seems to be 64 bit.

**Comment by frikinside** [comment]
![image](https://user-images.githubusercontent.com/13966372/123697140-d8c03c80-d85c-11eb-9505-06403340c40a.png)
Checking the Kernel architecture it says "armv7l". So it's 32 bits then.
So I guess I installed te right version of the apk, right?

**Comment by vhqtvn** [comment]
Yes i think so, still cant find a way to test on a 32bit device here (due to Covid lockdown), I'll update again later.

**Comment by vhqtvn** [comment]
Yes please try.

**Comment by frikinside** [comment]
I completly uninstall the current app, download the latest apk version from the repo, installed, promptme to install server at launch and.... crash at 0/0 like before.
So still having the same issue. Maybe when you fix or improve #121 it would solve this too.

**Comment by vhqtvn** [comment]
Your device has 4G ram right? That's quite enough...

**Comment by frikinside** [comment]
Yeah, 3850MB reads CPUZ, availiable 1230MB

**Comment by vhqtvn** [comment]
The latest version has crash information now, please try.

**Comment by frikinside** [comment]
I download the most recent version and crash at the same time, but this time (as you said) pop up the launch report, this is the full exception:
java.io.FileNotFoundException
java.io.FileNotFoundException

java.io.FileNotFoundException: /data/data/vn.vhn.vsc/files/code-server/release-standalone/ThirdPartyNotices.txt: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at vn.vhn.vhscode.CodeServerService$Companion.extractTarGz(CodeServerService.kt:28)
	at vn.vhn.vhscode.CodeServerService$Companion$c.invokeSuspend(Unknown Source:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7283)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 13 more


Android Version: 29
Device Manufacturer: JUSYEA
Device Model: J5

**Comment by vhqtvn** [comment]
`ThirdPartyNotices.txt` is the first file to be extracted, seems that creation of the folder `/data/data/vn.vhn.vsc/files/code-server/release-standalone` was failed.

I've added more checks, please try this version https://github.com/vhqtvn/VHEditor-Android/releases/tag/v2.7.2

**Comment by frikinside** [comment]
Now the error is the following:
Starting...
Removing old installation...
Preparing...
Total entry: 7591
Exception: java.io.IOException: Failed to create directory /data/data/vn.vhn.vsc
 at vn.vhn.vhscode.CodeServerServiceKt.mkdirs2(CodeServerService.kt:9)
 at vn.vhn.vhscode.CodeServerServiceKt.mkdirs2(CodeServerService.kt:5)
 at vn.vhn.vhscode.CodeServerServiceKt.mkdirs2(CodeServerService.kt:5)
 at vn.vhn.vhscode.CodeServerService$Companion.extractTarGz(CodeServerService.kt:19)
 at vn.vhn.vhscode.CodeServerService$Companion$c.invokeSuspend(Unknown Source:12)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:4)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7386)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

It happened on step 1/7591 of the install server process.
Looks like it cannot create that folder, but it doesn`t say why.
I double check if the app has storage permissons granted and it has.
